const activityData = {
  "weekly": {
    "start_date": "Monday, Jun 02, 2025",
    "end_date": "Monday, Jun 02, 2025",
    "total_hours": 0.0,
    "active_hours": 0.0,
    "active_percentage": 0,
    "afk_hours": 0.0,
    "afk_percentage": 0,
    "productive_hours": 0.0,
    "productive_percentage": 0,
    "non_productive_hours": 0.0,
    "non_productive_percentage": 0,
    "other_hours": 0.0,
    "other_percentage": 0,
    "labels": [],
    "productive": [],
    "non_productive": [],
    "other": [],
    "afk": [],
    "top_apps_labels": [],
    "top_apps_data": [],
    "top_apps_colors": [],
    "trend_labels": [],
    "trend_data": [],
    "hour_labels": [
      "0:00",
      "1:00",
      "2:00",
      "3:00",
      "4:00",
      "5:00",
      "6:00",
      "7:00",
      "8:00",
      "9:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00"
    ],
    "hour_data": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "categories": [],
    "category_data": [],
    "category_colors": [],
    "web_labels": [],
    "web_data": [],
    "web_colors": []
  },
  "daily": {
    "start_date": "Monday, Jun 02, 2025",
    "end_date": "Monday, Jun 02, 2025",
    "total_hours": 0.0,
    "active_hours": 0.0,
    "active_percentage": 0,
    "afk_hours": 0.0,
    "afk_percentage": 0,
    "productive_hours": 0.0,
    "productive_percentage": 0,
    "non_productive_hours": 0.0,
    "non_productive_percentage": 0,
    "other_hours": 0.0,
    "other_percentage": 0,
    "labels": [],
    "productive": [],
    "non_productive": [],
    "other": [],
    "afk": [],
    "top_apps_labels": [],
    "top_apps_data": [],
    "top_apps_colors": [],
    "trend_labels": [],
    "trend_data": [],
    "hour_labels": [
      "0:00",
      "1:00",
      "2:00",
      "3:00",
      "4:00",
      "5:00",
      "6:00",
      "7:00",
      "8:00",
      "9:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00"
    ],
    "hour_data": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "categories": [],
    "category_data": [],
    "category_colors": [],
    "web_labels": [],
    "web_data": [],
    "web_colors": []
  }
};